services:
  web-fastapi:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/messages_db
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - web-fastapi
    networks:
      - app-network
  mongo:
    image: mongo:4.4.6
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
  redis:
    image: redis:latest
    networks:
      - app-network
  bot:
    build: ./bot
    volumes:
      - ./bot:/bot
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/messages_db
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data: